param([Parameter(Mandatory=$true)][string]$CanonicalId)
$ErrorActionPreference='Stop';$root=Split-Path -Parent $PSScriptRoot
$catalogPath=Join-Path $root 'assets/data/exercise_library/movekit_complete_catalog.json';$manifestPath=Join-Path $root 'assets/data/exercise_library/anatomy_generation_manifest.json';$auditPath=Join-Path $root 'assets/data/exercise_library/anatomy_generation_audit.json';$checkpointPath=Join-Path $root 'assets/data/exercise_library/anatomy_generation_checkpoint.json'
$masterRelative='assets/exercises/anatomy/templates/male_neutral_anatomy_master_v4.png';$master=Join-Path $root $masterRelative;$masterHash='5FFE7590F204E01A1A1EC95B5D2312404B32A1FA59D2464E254D453254B95BD9'
if(-not(Test-Path $master)-or(Get-FileHash -Algorithm SHA256 $master).Hash-ne$masterHash){throw 'Locked Male V4 master missing or hash mismatch.'}
$catalog=Get-Content -Raw $catalogPath|ConvertFrom-Json;$exercise=$catalog.exercises|Where-Object canonical_id -eq $CanonicalId|Select-Object -First 1
if(-not$exercise-or$exercise.metadata_status-ne'metadata_validated'){throw 'Canonical exercise is missing or not metadata_validated.'}
$primary=@($exercise.primary_muscles);$secondary=@($exercise.secondary_muscles);$requested=@($primary)+@($secondary)
$supported=@('quadriceps','glutes','hamstrings','adductors');$unknown=@($requested|Where-Object {$_-notin$supported});if($unknown.Count){throw "No deterministic mask registered for: $($unknown-join', ')"}
$dir=Join-Path $root 'assets/exercises/anatomy/candidates/male';[IO.Directory]::CreateDirectory($dir)|Out-Null;$version=2;do{$stem="${CanonicalId}_v$version";$artwork=Join-Path $dir "${stem}_artwork.png";$card=Join-Path $dir "$stem.png";$version++}while((Test-Path $artwork)-or(Test-Path $card))
Add-Type -AssemblyName System.Drawing
function Add-Polygon($Graphics,[Drawing.Brush]$Brush,[int[]]$Coordinates){$points=@();for($i=0;$i-lt$Coordinates.Count;$i+=2){$points+=[Drawing.Point]::new($Coordinates[$i],$Coordinates[$i+1])};$Graphics.FillPolygon($Brush,$points)}
$mask=[Drawing.Bitmap]::new(1254,1254);$mg=[Drawing.Graphics]::FromImage($mask);$redBrush=[Drawing.SolidBrush]::new([Drawing.Color]::Red);$orangeBrush=[Drawing.SolidBrush]::new([Drawing.Color]::Orange)
try{$mg.Clear([Drawing.Color]::Black);$mg.SmoothingMode=[Drawing.Drawing2D.SmoothingMode]::AntiAlias
 $colors=@{};foreach($name in $primary){$colors[$name]=$redBrush};foreach($name in $secondary){if(-not$colors.ContainsKey($name)){$colors[$name]=$orangeBrush}}
 if($colors.quadriceps){Add-Polygon $mg $colors.quadriceps @(205,565,300,550,320,610,315,730,282,850,225,825,195,710);Add-Polygon $mg $colors.quadriceps @(395,550,490,565,510,710,480,825,423,850,390,730,388,610)}
 if($colors.adductors){Add-Polygon $mg $colors.adductors @(298,565,345,590,345,780,315,725,305,645);Add-Polygon $mg $colors.adductors @(350,590,397,565,390,645,380,725,350,780)}
 if($colors.glutes){Add-Polygon $mg $colors.glutes @(770,525,835,505,900,545,900,655,850,690,785,660,755,595);Add-Polygon $mg $colors.glutes @(910,545,975,505,1040,525,1055,595,1025,660,960,690,910,655)}
 if($colors.hamstrings){Add-Polygon $mg $colors.hamstrings @(770,650,850,670,890,700,875,845,820,900,770,855,750,745);Add-Polygon $mg $colors.hamstrings @(920,700,960,670,1040,650,1060,745,1040,855,990,900,935,845)}
}finally{$mg.Dispose();$redBrush.Dispose();$orangeBrush.Dispose()}
$source=[Drawing.Bitmap]::new($master);$output=[Drawing.Bitmap]::new(1254,1254)
try{for($y=0;$y-lt1254;$y++){for($x=0;$x-lt1254;$x++){$p=$source.GetPixel($x,$y);$m=$mask.GetPixel($x,$y);if($m.R-gt200-and$m.G-lt80){$lum=($p.R+$p.G+$p.B)/3;$output.SetPixel($x,$y,[Drawing.Color]::FromArgb([int](0.68*215+0.32*$lum),[int](0.68*45+0.32*$lum),[int](0.68*45+0.32*$lum)))}elseif($m.R-gt200-and$m.G-gt100){$lum=($p.R+$p.G+$p.B)/3;$output.SetPixel($x,$y,[Drawing.Color]::FromArgb([int](0.68*239+0.32*$lum),[int](0.68*132+0.32*$lum),[int](0.68*38+0.32*$lum)))}else{$output.SetPixel($x,$y,$p)}}};$scaled=[Drawing.Bitmap]::new(1024,1024);try{$g=[Drawing.Graphics]::FromImage($scaled);try{$g.InterpolationMode=[Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic;$g.DrawImage($output,0,0,1024,1024)}finally{$g.Dispose()};$stream=[IO.File]::Open($artwork,[IO.FileMode]::CreateNew);try{$scaled.Save($stream,[Drawing.Imaging.ImageFormat]::Png)}finally{$stream.Dispose()}}finally{$scaled.Dispose()}}finally{$source.Dispose();$output.Dispose();$mask.Dispose()}
$renderer=Join-Path $PSScriptRoot 'render_anatomy_card.ps1';$rendererFields=& $renderer -ArtworkPath $artwork -OutputPath $card -ExerciseName $exercise.display_name -PrimaryMuscles $primary -SecondaryMuscles $secondary|ConvertFrom-Json
$manifest=Get-Content -Raw $manifestPath|ConvertFrom-Json;$job=$manifest.jobs|Where-Object job_id -eq "${CanonicalId}_male"|Select-Object -First 1;if(-not$job){throw 'Male manifest job missing.'}
$priorPath=$job.output_path;$priorValidation=$job.validation_result;$priorStatus=$job.status
if($priorStatus-eq'pending_review'-and$priorPath-match'^assets/exercises/anatomy/candidates/') {if(-not$job.PSObject.Properties['candidate_history']){$job|Add-Member -NotePropertyName candidate_history -NotePropertyValue @()};$job.candidate_history=@($job.candidate_history)+@([ordered]@{status='superseded_layout_qa';superseded_at=(Get-Date).ToUniversalTime().ToString('o');output_path=$priorPath;validation_result=$priorValidation})}
$relativeCard=$card.Substring($root.Length+1).Replace('\','/');$relativeArtwork=$artwork.Substring($root.Length+1).Replace('\','/');$job.output_path=$relativeCard;$job.status='pending_review';$job.error_details=$null;$job.validation_result=[ordered]@{valid=$true;mode='deterministic_mask_compositor';width=1024;height=1024;master_path=$masterRelative;master_sha256=$masterHash;primary_muscles=$primary;secondary_muscles=$secondary;artwork_path=$relativeArtwork;renderer_fields=$rendererFields;generated_at=(Get-Date).ToUniversalTime().ToString('o');estimated_cost_usd=0.0}
[IO.File]::WriteAllText($manifestPath,($manifest|ConvertTo-Json -Depth 20)+[Environment]::NewLine,[Text.UTF8Encoding]::new($false));$audit=Get-Content -Raw $auditPath|ConvertFrom-Json;$audit.events=@($audit.events)+@([ordered]@{at=(Get-Date).ToUniversalTime().ToString('o');job_id=$job.job_id;action='deterministic_candidate_generated';details=($job.validation_result|ConvertTo-Json -Depth 12 -Compress)});[IO.File]::WriteAllText($auditPath,($audit|ConvertTo-Json -Depth 20)+[Environment]::NewLine,[Text.UTF8Encoding]::new($false))
[ordered]@{job_id=$job.job_id;status=$job.status;card_path=$relativeCard;artwork_path=$relativeArtwork;title=$exercise.display_name;primary_muscles=$primary;secondary_muscles=$secondary;width=1024;height=1024;estimated_cost_usd=0.0}|ConvertTo-Json -Depth 6 -Compress
