param([Parameter(Mandatory=$true)][string]$ArtworkPath,[Parameter(Mandatory=$true)][string]$Sex,[Parameter(Mandatory=$true)][string[]]$PrimaryMuscles,[Parameter(Mandatory=$true)][string[]]$SecondaryMuscles)
$ErrorActionPreference='Stop';if($Sex-ne'male'){throw 'male_only_validation'};Add-Type -AssemblyName System.Drawing;$image=[Drawing.Bitmap]::new($ArtworkPath)
try{
 if($image.Width-ne1024-or$image.Height-ne1024){throw 'artwork_dimensions_must_be_1024x1024'}
 $red=0;$orange=0;$leftBody=0;$rightBody=0;$nonWhiteMargin=0;$redChest=0;$orangeFrontDelts=0;$orangeBackTriceps=0;$orangeBackShoulders=0;$unrelatedBench=0
 for($y=0;$y-lt1024;$y+=2){for($x=0;$x-lt1024;$x+=2){$p=$image.GetPixel($x,$y);$isRed=$p.R-gt145-and$p.R-gt($p.G*1.35)-and$p.R-gt($p.B*1.35);$isOrange=$p.R-gt165-and$p.G-gt65-and$p.G-lt190-and$p.B-lt110-and$p.R-gt($p.G*1.15);$dark=$p.R-lt210-or$p.G-lt210-or$p.B-lt210;if($isRed){$red++};if($isOrange){$orange++};if($dark-and$x-lt500-and$y-gt40-and$y-lt1000){$leftBody++};if($dark-and$x-gt524-and$y-gt40-and$y-lt1000){$rightBody++};if(($x-lt20-or$x-gt1003-or$y-lt10-or$y-gt1013)-and$dark){$nonWhiteMargin++}
  $chest=$x-ge145-and$x-le455-and$y-ge190-and$y-le405;$frontDelts=(($x-ge65-and$x-le180)-or($x-ge400-and$x-le520))-and$y-ge175-and$y-le360;$backTriceps=(($x-ge540-and$x-le675)-or($x-ge865-and$x-le1000))-and$y-ge300-and$y-le575;$backShoulders=(($x-ge530-and$x-le700)-or($x-ge820-and$x-le1000))-and$y-ge175-and$y-le320
  if($isRed-and$chest){$redChest++};if($isOrange-and$frontDelts){$orangeFrontDelts++};if($isOrange-and$backTriceps){$orangeBackTriceps++};if($isOrange-and$backShoulders){$orangeBackShoulders++};if(($isRed-or$isOrange)-and-not($chest-or$frontDelts-or$backTriceps)){$unrelatedBench++}
 }}
 $metrics=[ordered]@{red_samples=$red;orange_samples=$orange;front_body_samples=$leftBody;back_body_samples=$rightBody;non_white_margin_samples=$nonWhiteMargin;red_chest_samples=$redChest;orange_front_deltoid_samples=$orangeFrontDelts;orange_back_triceps_samples=$orangeBackTriceps;orange_back_shoulder_samples=$orangeBackShoulders;unrelated_bench_color_samples=$unrelatedBench}
 if($nonWhiteMargin-gt8){throw 'artwork_contains_text_ui_or_inherited_content'};if($leftBody-lt5000-or$rightBody-lt5000){throw 'missing_true_front_or_back_male_anatomy'};if($red-lt80){throw 'missing_primary_red_highlights'};if($SecondaryMuscles.Count-and$orange-lt40){throw 'missing_secondary_orange_highlights'};if(-not$SecondaryMuscles.Count-and$orange-gt20){throw 'unexpected_secondary_orange_highlights'}
 $bench=(@($PrimaryMuscles)-join',')-eq'chest'-and(@($SecondaryMuscles)-join',')-eq'anterior_deltoids,triceps'
 if($bench){if($redChest-lt80){throw 'missing_red_front_chest'};if($orangeFrontDelts-lt50){throw 'missing_orange_front_anterior_deltoids'};if($orangeBackTriceps-lt50){throw 'missing_orange_back_triceps'};if($orangeBackShoulders-gt20){throw 'orange_back_shoulder_caps_forbidden'};if($unrelatedBench-gt30){throw 'unrelated_colored_regions_detected'}}
}finally{$image.Dispose()}
[ordered]@{valid=$true;text_detected=$false;renderer_allowed=$true;sex='male';rules=if($bench){'male_bench_press_strict'}else{'male_catalog_color_isolation'};primary_muscles=@($PrimaryMuscles);secondary_muscles=@($SecondaryMuscles);pixel_metrics=$metrics}|ConvertTo-Json -Depth 6 -Compress
